// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm.proto

package com.lz.game.fund.comm.proto;

public final class CommProto {
  private CommProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcRequestOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<RpcRequest> {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // optional string sess_id = 2;
    boolean hasSessId();
    String getSessId();
    
    // required int32 service = 3;
    boolean hasService();
    int getService();
    
    // required int32 method = 4;
    boolean hasMethod();
    int getMethod();
    
    // optional int32 ecc = 5;
    boolean hasEcc();
    int getEcc();
    
    // optional bytes proto_param = 6;
    boolean hasProtoParam();
    com.google.protobuf.ByteString getProtoParam();
    
    // optional int32 reserved = 7;
    boolean hasReserved();
    int getReserved();
  }
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        RpcRequest> implements RpcRequestOrBuilder {
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(Builder builder) {
      super(builder);
    }
    private RpcRequest(boolean noInit) {}
    
    private static final RpcRequest defaultInstance;
    public static RpcRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // optional string sess_id = 2;
    public static final int SESS_ID_FIELD_NUMBER = 2;
    private java.lang.Object sessId_;
    public boolean hasSessId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSessId() {
      java.lang.Object ref = sessId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessIdBytes() {
      java.lang.Object ref = sessId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private int service_;
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getService() {
      return service_;
    }
    
    // required int32 method = 4;
    public static final int METHOD_FIELD_NUMBER = 4;
    private int method_;
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMethod() {
      return method_;
    }
    
    // optional int32 ecc = 5;
    public static final int ECC_FIELD_NUMBER = 5;
    private int ecc_;
    public boolean hasEcc() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getEcc() {
      return ecc_;
    }
    
    // optional bytes proto_param = 6;
    public static final int PROTO_PARAM_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString protoParam_;
    public boolean hasProtoParam() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getProtoParam() {
      return protoParam_;
    }
    
    // optional int32 reserved = 7;
    public static final int RESERVED_FIELD_NUMBER = 7;
    private int reserved_;
    public boolean hasReserved() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getReserved() {
      return reserved_;
    }
    
    private void initFields() {
      id_ = 0;
      sessId_ = "";
      service_ = 0;
      method_ = 0;
      ecc_ = 0;
      protoParam_ = com.google.protobuf.ByteString.EMPTY;
      reserved_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.lz.game.fund.comm.proto.CommProto.RpcRequest>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, service_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, method_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, ecc_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, protoParam_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, reserved_);
      }
      extensionWriter.writeUntil(1000, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, service_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, method_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, ecc_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, protoParam_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, reserved_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lz.game.fund.comm.proto.CommProto.RpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.lz.game.fund.comm.proto.CommProto.RpcRequest, Builder> implements com.lz.game.fund.comm.proto.CommProto.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcRequest_fieldAccessorTable;
      }
      
      // Construct using com.lz.game.fund.comm.proto.CommProto.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        service_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        ecc_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        protoParam_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        reserved_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lz.game.fund.comm.proto.CommProto.RpcRequest.getDescriptor();
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcRequest getDefaultInstanceForType() {
        return com.lz.game.fund.comm.proto.CommProto.RpcRequest.getDefaultInstance();
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcRequest build() {
        com.lz.game.fund.comm.proto.CommProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lz.game.fund.comm.proto.CommProto.RpcRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lz.game.fund.comm.proto.CommProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcRequest buildPartial() {
        com.lz.game.fund.comm.proto.CommProto.RpcRequest result = new com.lz.game.fund.comm.proto.CommProto.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessId_ = sessId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ecc_ = ecc_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.protoParam_ = protoParam_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.reserved_ = reserved_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lz.game.fund.comm.proto.CommProto.RpcRequest) {
          return mergeFrom((com.lz.game.fund.comm.proto.CommProto.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lz.game.fund.comm.proto.CommProto.RpcRequest other) {
        if (other == com.lz.game.fund.comm.proto.CommProto.RpcRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSessId()) {
          setSessId(other.getSessId());
        }
        if (other.hasService()) {
          setService(other.getService());
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasEcc()) {
          setEcc(other.getEcc());
        }
        if (other.hasProtoParam()) {
          setProtoParam(other.getProtoParam());
        }
        if (other.hasReserved()) {
          setReserved(other.getReserved());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasService()) {
          
          return false;
        }
        if (!hasMethod()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              service_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              method_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ecc_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              protoParam_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              reserved_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string sess_id = 2;
      private java.lang.Object sessId_ = "";
      public boolean hasSessId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSessId() {
        java.lang.Object ref = sessId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessId_ = getDefaultInstance().getSessId();
        onChanged();
        return this;
      }
      void setSessId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sessId_ = value;
        onChanged();
      }
      
      // required int32 service = 3;
      private int service_ ;
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getService() {
        return service_;
      }
      public Builder setService(int value) {
        bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000004);
        service_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 method = 4;
      private int method_ ;
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMethod() {
        return method_;
      }
      public Builder setMethod(int value) {
        bitField0_ |= 0x00000008;
        method_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        method_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 ecc = 5;
      private int ecc_ ;
      public boolean hasEcc() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getEcc() {
        return ecc_;
      }
      public Builder setEcc(int value) {
        bitField0_ |= 0x00000010;
        ecc_ = value;
        onChanged();
        return this;
      }
      public Builder clearEcc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ecc_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes proto_param = 6;
      private com.google.protobuf.ByteString protoParam_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasProtoParam() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getProtoParam() {
        return protoParam_;
      }
      public Builder setProtoParam(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        protoParam_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoParam() {
        bitField0_ = (bitField0_ & ~0x00000020);
        protoParam_ = getDefaultInstance().getProtoParam();
        onChanged();
        return this;
      }
      
      // optional int32 reserved = 7;
      private int reserved_ ;
      public boolean hasReserved() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getReserved() {
        return reserved_;
      }
      public Builder setReserved(int value) {
        bitField0_ |= 0x00000040;
        reserved_ = value;
        onChanged();
        return this;
      }
      public Builder clearReserved() {
        bitField0_ = (bitField0_ & ~0x00000040);
        reserved_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.RpcRequest)
    }
    
    static {
      defaultInstance = new RpcRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.RpcRequest)
  }
  
  public interface RpcResponseOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<RpcResponse> {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // optional string sess_id = 2;
    boolean hasSessId();
    String getSessId();
    
    // required int32 service = 3;
    boolean hasService();
    int getService();
    
    // required int32 method = 4;
    boolean hasMethod();
    int getMethod();
    
    // required bool is_failed = 5;
    boolean hasIsFailed();
    boolean getIsFailed();
    
    // optional int32 error_code = 6;
    boolean hasErrorCode();
    int getErrorCode();
    
    // optional string error_msg = 7;
    boolean hasErrorMsg();
    String getErrorMsg();
    
    // optional bytes proto_param = 8;
    boolean hasProtoParam();
    com.google.protobuf.ByteString getProtoParam();
    
    // optional int32 reserved = 9;
    boolean hasReserved();
    int getReserved();
  }
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        RpcResponse> implements RpcResponseOrBuilder {
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(Builder builder) {
      super(builder);
    }
    private RpcResponse(boolean noInit) {}
    
    private static final RpcResponse defaultInstance;
    public static RpcResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RpcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // optional string sess_id = 2;
    public static final int SESS_ID_FIELD_NUMBER = 2;
    private java.lang.Object sessId_;
    public boolean hasSessId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSessId() {
      java.lang.Object ref = sessId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessIdBytes() {
      java.lang.Object ref = sessId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 service = 3;
    public static final int SERVICE_FIELD_NUMBER = 3;
    private int service_;
    public boolean hasService() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getService() {
      return service_;
    }
    
    // required int32 method = 4;
    public static final int METHOD_FIELD_NUMBER = 4;
    private int method_;
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getMethod() {
      return method_;
    }
    
    // required bool is_failed = 5;
    public static final int IS_FAILED_FIELD_NUMBER = 5;
    private boolean isFailed_;
    public boolean hasIsFailed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getIsFailed() {
      return isFailed_;
    }
    
    // optional int32 error_code = 6;
    public static final int ERROR_CODE_FIELD_NUMBER = 6;
    private int errorCode_;
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getErrorCode() {
      return errorCode_;
    }
    
    // optional string error_msg = 7;
    public static final int ERROR_MSG_FIELD_NUMBER = 7;
    private java.lang.Object errorMsg_;
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes proto_param = 8;
    public static final int PROTO_PARAM_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString protoParam_;
    public boolean hasProtoParam() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getProtoParam() {
      return protoParam_;
    }
    
    // optional int32 reserved = 9;
    public static final int RESERVED_FIELD_NUMBER = 9;
    private int reserved_;
    public boolean hasReserved() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getReserved() {
      return reserved_;
    }
    
    private void initFields() {
      id_ = 0;
      sessId_ = "";
      service_ = 0;
      method_ = 0;
      isFailed_ = false;
      errorCode_ = 0;
      errorMsg_ = "";
      protoParam_ = com.google.protobuf.ByteString.EMPTY;
      reserved_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsFailed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.lz.game.fund.comm.proto.CommProto.RpcResponse>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, service_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, method_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isFailed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, errorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, protoParam_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, reserved_);
      }
      extensionWriter.writeUntil(1000, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, service_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, method_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isFailed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, errorCode_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, protoParam_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, reserved_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.lz.game.fund.comm.proto.CommProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lz.game.fund.comm.proto.CommProto.RpcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.lz.game.fund.comm.proto.CommProto.RpcResponse, Builder> implements com.lz.game.fund.comm.proto.CommProto.RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lz.game.fund.comm.proto.CommProto.internal_static_proto_RpcResponse_fieldAccessorTable;
      }
      
      // Construct using com.lz.game.fund.comm.proto.CommProto.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sessId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        service_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        method_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        isFailed_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        protoParam_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        reserved_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lz.game.fund.comm.proto.CommProto.RpcResponse.getDescriptor();
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcResponse getDefaultInstanceForType() {
        return com.lz.game.fund.comm.proto.CommProto.RpcResponse.getDefaultInstance();
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcResponse build() {
        com.lz.game.fund.comm.proto.CommProto.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.lz.game.fund.comm.proto.CommProto.RpcResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.lz.game.fund.comm.proto.CommProto.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.lz.game.fund.comm.proto.CommProto.RpcResponse buildPartial() {
        com.lz.game.fund.comm.proto.CommProto.RpcResponse result = new com.lz.game.fund.comm.proto.CommProto.RpcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessId_ = sessId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.service_ = service_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isFailed_ = isFailed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.errorMsg_ = errorMsg_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.protoParam_ = protoParam_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.reserved_ = reserved_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lz.game.fund.comm.proto.CommProto.RpcResponse) {
          return mergeFrom((com.lz.game.fund.comm.proto.CommProto.RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.lz.game.fund.comm.proto.CommProto.RpcResponse other) {
        if (other == com.lz.game.fund.comm.proto.CommProto.RpcResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSessId()) {
          setSessId(other.getSessId());
        }
        if (other.hasService()) {
          setService(other.getService());
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasIsFailed()) {
          setIsFailed(other.getIsFailed());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorMsg()) {
          setErrorMsg(other.getErrorMsg());
        }
        if (other.hasProtoParam()) {
          setProtoParam(other.getProtoParam());
        }
        if (other.hasReserved()) {
          setReserved(other.getReserved());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasService()) {
          
          return false;
        }
        if (!hasMethod()) {
          
          return false;
        }
        if (!hasIsFailed()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              service_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              method_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isFailed_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              errorCode_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              errorMsg_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              protoParam_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              reserved_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional string sess_id = 2;
      private java.lang.Object sessId_ = "";
      public boolean hasSessId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSessId() {
        java.lang.Object ref = sessId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessId_ = getDefaultInstance().getSessId();
        onChanged();
        return this;
      }
      void setSessId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        sessId_ = value;
        onChanged();
      }
      
      // required int32 service = 3;
      private int service_ ;
      public boolean hasService() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getService() {
        return service_;
      }
      public Builder setService(int value) {
        bitField0_ |= 0x00000004;
        service_ = value;
        onChanged();
        return this;
      }
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000004);
        service_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 method = 4;
      private int method_ ;
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getMethod() {
        return method_;
      }
      public Builder setMethod(int value) {
        bitField0_ |= 0x00000008;
        method_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        method_ = 0;
        onChanged();
        return this;
      }
      
      // required bool is_failed = 5;
      private boolean isFailed_ ;
      public boolean hasIsFailed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getIsFailed() {
        return isFailed_;
      }
      public Builder setIsFailed(boolean value) {
        bitField0_ |= 0x00000010;
        isFailed_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsFailed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isFailed_ = false;
        onChanged();
        return this;
      }
      
      // optional int32 error_code = 6;
      private int errorCode_ ;
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getErrorCode() {
        return errorCode_;
      }
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000020;
        errorCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        errorCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string error_msg = 7;
      private java.lang.Object errorMsg_ = "";
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000040);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      void setErrorMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        errorMsg_ = value;
        onChanged();
      }
      
      // optional bytes proto_param = 8;
      private com.google.protobuf.ByteString protoParam_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasProtoParam() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getProtoParam() {
        return protoParam_;
      }
      public Builder setProtoParam(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        protoParam_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoParam() {
        bitField0_ = (bitField0_ & ~0x00000080);
        protoParam_ = getDefaultInstance().getProtoParam();
        onChanged();
        return this;
      }
      
      // optional int32 reserved = 9;
      private int reserved_ ;
      public boolean hasReserved() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getReserved() {
        return reserved_;
      }
      public Builder setReserved(int value) {
        bitField0_ |= 0x00000100;
        reserved_ = value;
        onChanged();
        return this;
      }
      public Builder clearReserved() {
        bitField0_ = (bitField0_ & ~0x00000100);
        reserved_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.RpcResponse)
    }
    
    static {
      defaultInstance = new RpcResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.RpcResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RpcRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RpcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_RpcResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncomm.proto\022\005proto\"\205\001\n\nRpcRequest\022\n\n\002id" +
      "\030\001 \002(\005\022\017\n\007sess_id\030\002 \001(\t\022\017\n\007service\030\003 \002(\005" +
      "\022\016\n\006method\030\004 \002(\005\022\013\n\003ecc\030\005 \001(\005\022\023\n\013proto_p" +
      "aram\030\006 \001(\014\022\020\n\010reserved\030\007 \001(\005*\005\010d\020\350\007\"\263\001\n\013" +
      "RpcResponse\022\n\n\002id\030\001 \002(\005\022\017\n\007sess_id\030\002 \001(\t" +
      "\022\017\n\007service\030\003 \002(\005\022\016\n\006method\030\004 \002(\005\022\021\n\tis_" +
      "failed\030\005 \002(\010\022\022\n\nerror_code\030\006 \001(\005\022\021\n\terro" +
      "r_msg\030\007 \001(\t\022\023\n\013proto_param\030\010 \001(\014\022\020\n\010rese" +
      "rved\030\t \001(\005*\005\010d\020\350\007B0\n\033com.lz.game.fund.co" +
      "mm.protoB\tCommProtoH\001\200\001\000\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_RpcRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_RpcRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_RpcRequest_descriptor,
              new java.lang.String[] { "Id", "SessId", "Service", "Method", "Ecc", "ProtoParam", "Reserved", },
              com.lz.game.fund.comm.proto.CommProto.RpcRequest.class,
              com.lz.game.fund.comm.proto.CommProto.RpcRequest.Builder.class);
          internal_static_proto_RpcResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_RpcResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_RpcResponse_descriptor,
              new java.lang.String[] { "Id", "SessId", "Service", "Method", "IsFailed", "ErrorCode", "ErrorMsg", "ProtoParam", "Reserved", },
              com.lz.game.fund.comm.proto.CommProto.RpcResponse.class,
              com.lz.game.fund.comm.proto.CommProto.RpcResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
