// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway.proto

package com.lz.game.platf.gateway.proto;

public final class GatewayProto {
  private GatewayProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MethodNameForGateway
      implements com.google.protobuf.ProtocolMessageEnum {
    CREATE_CLIENT_SESSION(0, 1),
    ;
    
    public static final int CREATE_CLIENT_SESSION_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static MethodNameForGateway valueOf(int value) {
      switch (value) {
        case 1: return CREATE_CLIENT_SESSION;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MethodNameForGateway>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MethodNameForGateway>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MethodNameForGateway>() {
            public MethodNameForGateway findValueByNumber(int number) {
              return MethodNameForGateway.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GatewayProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MethodNameForGateway[] VALUES = {
      CREATE_CLIENT_SESSION, 
    };
    
    public static MethodNameForGateway valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MethodNameForGateway(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.MethodNameForGateway)
  }
  
  public enum ErrorCodeForGateway
      implements com.google.protobuf.ProtocolMessageEnum {
    CONN_GAMESERVER_FAILED(0, 301),
    INVALID_ACCESS_TOKEN(1, 302),
    ;
    
    public static final int CONN_GAMESERVER_FAILED_VALUE = 301;
    public static final int INVALID_ACCESS_TOKEN_VALUE = 302;
    
    
    public final int getNumber() { return value; }
    
    public static ErrorCodeForGateway valueOf(int value) {
      switch (value) {
        case 301: return CONN_GAMESERVER_FAILED;
        case 302: return INVALID_ACCESS_TOKEN;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCodeForGateway>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCodeForGateway>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCodeForGateway>() {
            public ErrorCodeForGateway findValueByNumber(int number) {
              return ErrorCodeForGateway.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GatewayProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final ErrorCodeForGateway[] VALUES = {
      CONN_GAMESERVER_FAILED, INVALID_ACCESS_TOKEN, 
    };
    
    public static ErrorCodeForGateway valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ErrorCodeForGateway(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.ErrorCodeForGateway)
  }
  
  public interface ConnectGatewayReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string player_account = 1;
    boolean hasPlayerAccount();
    String getPlayerAccount();
    
    // required string access_token = 2;
    boolean hasAccessToken();
    String getAccessToken();
    
    // required int32 logical_server_id = 3;
    boolean hasLogicalServerId();
    int getLogicalServerId();
    
    // optional string device_id = 4;
    boolean hasDeviceId();
    String getDeviceId();
    
    // optional .proto.SrcChannel src_channel = 5;
    boolean hasSrcChannel();
    com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel getSrcChannel();
  }
  public static final class ConnectGatewayReq extends
      com.google.protobuf.GeneratedMessage
      implements ConnectGatewayReqOrBuilder {
    // Use ConnectGatewayReq.newBuilder() to construct.
    private ConnectGatewayReq(Builder builder) {
      super(builder);
    }
    private ConnectGatewayReq(boolean noInit) {}
    
    private static final ConnectGatewayReq defaultInstance;
    public static ConnectGatewayReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectGatewayReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GatewayProto.internal_static_proto_ConnectGatewayReq_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GatewayProto.internal_static_proto_ConnectGatewayReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string player_account = 1;
    public static final int PLAYER_ACCOUNT_FIELD_NUMBER = 1;
    private Object playerAccount_;
    public boolean hasPlayerAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPlayerAccount() {
      Object ref = playerAccount_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          playerAccount_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlayerAccountBytes() {
      Object ref = playerAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        playerAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string access_token = 2;
    public static final int ACCESS_TOKEN_FIELD_NUMBER = 2;
    private Object accessToken_;
    public boolean hasAccessToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAccessToken() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accessToken_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 logical_server_id = 3;
    public static final int LOGICAL_SERVER_ID_FIELD_NUMBER = 3;
    private int logicalServerId_;
    public boolean hasLogicalServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLogicalServerId() {
      return logicalServerId_;
    }
    
    // optional string device_id = 4;
    public static final int DEVICE_ID_FIELD_NUMBER = 4;
    private Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .proto.SrcChannel src_channel = 5;
    public static final int SRC_CHANNEL_FIELD_NUMBER = 5;
    private com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel srcChannel_;
    public boolean hasSrcChannel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel getSrcChannel() {
      return srcChannel_;
    }
    
    private void initFields() {
      playerAccount_ = "";
      accessToken_ = "";
      logicalServerId_ = 0;
      deviceId_ = "";
      srcChannel_ = com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel.OFFICIAL;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccessToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLogicalServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlayerAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccessTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, logicalServerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, srcChannel_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlayerAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccessTokenBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, logicalServerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, srcChannel_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ConnectGatewayReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ConnectGatewayReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ConnectGatewayReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ConnectGatewayReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ConnectGatewayReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ConnectGatewayReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ConnectGatewayReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ConnectGatewayReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ConnectGatewayReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GatewayProto.internal_static_proto_ConnectGatewayReq_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GatewayProto.internal_static_proto_ConnectGatewayReq_fieldAccessorTable;
      }
      
      // Construct using com.lz.game.platf.gateway.proto.GatewayProto.ConnectGatewayReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerAccount_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accessToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        logicalServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        srcChannel_ = com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel.OFFICIAL;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConnectGatewayReq.getDescriptor();
      }
      
      public ConnectGatewayReq getDefaultInstanceForType() {
        return ConnectGatewayReq.getDefaultInstance();
      }
      
      public ConnectGatewayReq build() {
        ConnectGatewayReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ConnectGatewayReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ConnectGatewayReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ConnectGatewayReq buildPartial() {
        ConnectGatewayReq result = new ConnectGatewayReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerAccount_ = playerAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accessToken_ = accessToken_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.logicalServerId_ = logicalServerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.srcChannel_ = srcChannel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectGatewayReq) {
          return mergeFrom((ConnectGatewayReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ConnectGatewayReq other) {
        if (other == ConnectGatewayReq.getDefaultInstance()) return this;
        if (other.hasPlayerAccount()) {
          setPlayerAccount(other.getPlayerAccount());
        }
        if (other.hasAccessToken()) {
          setAccessToken(other.getAccessToken());
        }
        if (other.hasLogicalServerId()) {
          setLogicalServerId(other.getLogicalServerId());
        }
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasSrcChannel()) {
          setSrcChannel(other.getSrcChannel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerAccount()) {
          
          return false;
        }
        if (!hasAccessToken()) {
          
          return false;
        }
        if (!hasLogicalServerId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              playerAccount_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accessToken_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              logicalServerId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceId_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel value = com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                srcChannel_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string player_account = 1;
      private Object playerAccount_ = "";
      public boolean hasPlayerAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPlayerAccount() {
        Object ref = playerAccount_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          playerAccount_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlayerAccount(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        playerAccount_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerAccount_ = getDefaultInstance().getPlayerAccount();
        onChanged();
        return this;
      }
      void setPlayerAccount(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        playerAccount_ = value;
        onChanged();
      }
      
      // required string access_token = 2;
      private Object accessToken_ = "";
      public boolean hasAccessToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAccessToken() {
        Object ref = accessToken_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccessToken(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccessToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      void setAccessToken(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        accessToken_ = value;
        onChanged();
      }
      
      // required int32 logical_server_id = 3;
      private int logicalServerId_ ;
      public boolean hasLogicalServerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLogicalServerId() {
        return logicalServerId_;
      }
      public Builder setLogicalServerId(int value) {
        bitField0_ |= 0x00000004;
        logicalServerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLogicalServerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        logicalServerId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string device_id = 4;
      private Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        deviceId_ = value;
        onChanged();
      }
      
      // optional .proto.SrcChannel src_channel = 5;
      private com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel srcChannel_ = com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel.OFFICIAL;
      public boolean hasSrcChannel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel getSrcChannel() {
        return srcChannel_;
      }
      public Builder setSrcChannel(com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        srcChannel_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcChannel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        srcChannel_ = com.lz.game.platf.global.proto.SrcChannelProto.SrcChannel.OFFICIAL;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.ConnectGatewayReq)
    }
    
    static {
      defaultInstance = new ConnectGatewayReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.ConnectGatewayReq)
  }
  
  public interface ConnectGatewayRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 player_id = 1;
    boolean hasPlayerId();
    int getPlayerId();
    
    // optional string chat_server_host = 2;
    boolean hasChatServerHost();
    String getChatServerHost();
    
    // optional int32 chat_server_port = 4;
    boolean hasChatServerPort();
    int getChatServerPort();
  }
  public static final class ConnectGatewayResp extends
      com.google.protobuf.GeneratedMessage
      implements ConnectGatewayRespOrBuilder {
    // Use ConnectGatewayResp.newBuilder() to construct.
    private ConnectGatewayResp(Builder builder) {
      super(builder);
    }
    private ConnectGatewayResp(boolean noInit) {}
    
    private static final ConnectGatewayResp defaultInstance;
    public static ConnectGatewayResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectGatewayResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GatewayProto.internal_static_proto_ConnectGatewayResp_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GatewayProto.internal_static_proto_ConnectGatewayResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 player_id = 1;
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    private int playerId_;
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPlayerId() {
      return playerId_;
    }
    
    // optional string chat_server_host = 2;
    public static final int CHAT_SERVER_HOST_FIELD_NUMBER = 2;
    private Object chatServerHost_;
    public boolean hasChatServerHost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getChatServerHost() {
      Object ref = chatServerHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          chatServerHost_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getChatServerHostBytes() {
      Object ref = chatServerHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        chatServerHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 chat_server_port = 4;
    public static final int CHAT_SERVER_PORT_FIELD_NUMBER = 4;
    private int chatServerPort_;
    public boolean hasChatServerPort() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getChatServerPort() {
      return chatServerPort_;
    }
    
    private void initFields() {
      playerId_ = 0;
      chatServerHost_ = "";
      chatServerPort_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChatServerHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, chatServerPort_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChatServerHostBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chatServerPort_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ConnectGatewayResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ConnectGatewayResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ConnectGatewayResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ConnectGatewayResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ConnectGatewayResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ConnectGatewayResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ConnectGatewayResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ConnectGatewayResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ConnectGatewayResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ConnectGatewayRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GatewayProto.internal_static_proto_ConnectGatewayResp_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GatewayProto.internal_static_proto_ConnectGatewayResp_fieldAccessorTable;
      }
      
      // Construct using com.lz.game.platf.gateway.proto.GatewayProto.ConnectGatewayResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        playerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        chatServerHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chatServerPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConnectGatewayResp.getDescriptor();
      }
      
      public ConnectGatewayResp getDefaultInstanceForType() {
        return ConnectGatewayResp.getDefaultInstance();
      }
      
      public ConnectGatewayResp build() {
        ConnectGatewayResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ConnectGatewayResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ConnectGatewayResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ConnectGatewayResp buildPartial() {
        ConnectGatewayResp result = new ConnectGatewayResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chatServerHost_ = chatServerHost_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chatServerPort_ = chatServerPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectGatewayResp) {
          return mergeFrom((ConnectGatewayResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ConnectGatewayResp other) {
        if (other == ConnectGatewayResp.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasChatServerHost()) {
          setChatServerHost(other.getChatServerHost());
        }
        if (other.hasChatServerPort()) {
          setChatServerPort(other.getChatServerPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              chatServerHost_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              chatServerPort_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 player_id = 1;
      private int playerId_ ;
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPlayerId() {
        return playerId_;
      }
      public Builder setPlayerId(int value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string chat_server_host = 2;
      private Object chatServerHost_ = "";
      public boolean hasChatServerHost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getChatServerHost() {
        Object ref = chatServerHost_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          chatServerHost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setChatServerHost(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chatServerHost_ = value;
        onChanged();
        return this;
      }
      public Builder clearChatServerHost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chatServerHost_ = getDefaultInstance().getChatServerHost();
        onChanged();
        return this;
      }
      void setChatServerHost(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        chatServerHost_ = value;
        onChanged();
      }
      
      // optional int32 chat_server_port = 4;
      private int chatServerPort_ ;
      public boolean hasChatServerPort() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getChatServerPort() {
        return chatServerPort_;
      }
      public Builder setChatServerPort(int value) {
        bitField0_ |= 0x00000004;
        chatServerPort_ = value;
        onChanged();
        return this;
      }
      public Builder clearChatServerPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chatServerPort_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.ConnectGatewayResp)
    }
    
    static {
      defaultInstance = new ConnectGatewayResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.ConnectGatewayResp)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ConnectGatewayReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ConnectGatewayReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ConnectGatewayResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ConnectGatewayResp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rgateway.proto\022\005proto\032\021src_channel.prot" +
      "o\"\227\001\n\021ConnectGatewayReq\022\026\n\016player_accoun" +
      "t\030\001 \002(\t\022\024\n\014access_token\030\002 \002(\t\022\031\n\021logical" +
      "_server_id\030\003 \002(\005\022\021\n\tdevice_id\030\004 \001(\t\022&\n\013s" +
      "rc_channel\030\005 \001(\0162\021.proto.SrcChannel\"[\n\022C" +
      "onnectGatewayResp\022\021\n\tplayer_id\030\001 \002(\005\022\030\n\020" +
      "chat_server_host\030\002 \001(\t\022\030\n\020chat_server_po" +
      "rt\030\004 \001(\005*1\n\024MethodNameForGateway\022\031\n\025CREA" +
      "TE_CLIENT_SESSION\020\001*M\n\023ErrorCodeForGatew" +
      "ay\022\033\n\026CONN_GAMESERVER_FAILED\020\255\002\022\031\n\024INVAL",
      "ID_ACCESS_TOKEN\020\256\002B1\n\037com.lz.game.platf." +
      "gateway.protoB\014GatewayProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ConnectGatewayReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ConnectGatewayReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ConnectGatewayReq_descriptor,
              new String[] { "PlayerAccount", "AccessToken", "LogicalServerId", "DeviceId", "SrcChannel", },
              ConnectGatewayReq.class,
              ConnectGatewayReq.Builder.class);
          internal_static_proto_ConnectGatewayResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_ConnectGatewayResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ConnectGatewayResp_descriptor,
              new String[] { "PlayerId", "ChatServerHost", "ChatServerPort", },
              ConnectGatewayResp.class,
              ConnectGatewayResp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.lz.game.platf.global.proto.SrcChannelProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
