// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_name.proto

package com.lz.game.platf.global.proto;

public final class ServiceNameProto {
  private ServiceNameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ServiceName
      implements com.google.protobuf.ProtocolMessageEnum {
    INTERNAL(0, 1),
    AUTH(1, 2),
    GATEWAY(2, 3),
    GAME_SERVER(3, 4),
    GAME_MGMT(4, 5),
    SYSTEM(5, 6),
    CHAT_SERVER(6, 7),
    CLIENTINTERNAL(7, 99),
    PLAYER(8, 101),
    BAG(9, 102),
    EQUIP(10, 103),
    WUXING(11, 104),
    TREE(12, 105),
    MAP(13, 106),
    STEAL_ROB(14, 107),
    ARENA(15, 108),
    SHOP(16, 109),
    ACTIVITY(17, 110),
    PAYMENT(18, 111),
    ;
    
    public static final int INTERNAL_VALUE = 1;
    public static final int AUTH_VALUE = 2;
    public static final int GATEWAY_VALUE = 3;
    public static final int GAME_SERVER_VALUE = 4;
    public static final int GAME_MGMT_VALUE = 5;
    public static final int SYSTEM_VALUE = 6;
    public static final int CHAT_SERVER_VALUE = 7;
    public static final int CLIENTINTERNAL_VALUE = 99;
    public static final int PLAYER_VALUE = 101;
    public static final int BAG_VALUE = 102;
    public static final int EQUIP_VALUE = 103;
    public static final int WUXING_VALUE = 104;
    public static final int TREE_VALUE = 105;
    public static final int MAP_VALUE = 106;
    public static final int STEAL_ROB_VALUE = 107;
    public static final int ARENA_VALUE = 108;
    public static final int SHOP_VALUE = 109;
    public static final int ACTIVITY_VALUE = 110;
    public static final int PAYMENT_VALUE = 111;
    
    
    public final int getNumber() { return value; }
    
    public static ServiceName valueOf(int value) {
      switch (value) {
        case 1: return INTERNAL;
        case 2: return AUTH;
        case 3: return GATEWAY;
        case 4: return GAME_SERVER;
        case 5: return GAME_MGMT;
        case 6: return SYSTEM;
        case 7: return CHAT_SERVER;
        case 99: return CLIENTINTERNAL;
        case 101: return PLAYER;
        case 102: return BAG;
        case 103: return EQUIP;
        case 104: return WUXING;
        case 105: return TREE;
        case 106: return MAP;
        case 107: return STEAL_ROB;
        case 108: return ARENA;
        case 109: return SHOP;
        case 110: return ACTIVITY;
        case 111: return PAYMENT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ServiceName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ServiceName>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceName>() {
            public ServiceName findValueByNumber(int number) {
              return ServiceName.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lz.game.platf.global.proto.ServiceNameProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ServiceName[] VALUES = {
      INTERNAL, AUTH, GATEWAY, GAME_SERVER, GAME_MGMT, SYSTEM, CHAT_SERVER, CLIENTINTERNAL, PLAYER, BAG, EQUIP, WUXING, TREE, MAP, STEAL_ROB, ARENA, SHOP, ACTIVITY, PAYMENT, 
    };
    
    public static ServiceName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ServiceName(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:proto.ServiceName)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022service_name.proto\022\005proto*\201\002\n\013ServiceN" +
      "ame\022\014\n\010INTERNAL\020\001\022\010\n\004AUTH\020\002\022\013\n\007GATEWAY\020\003" +
      "\022\017\n\013GAME_SERVER\020\004\022\r\n\tGAME_MGMT\020\005\022\n\n\006SYST" +
      "EM\020\006\022\017\n\013CHAT_SERVER\020\007\022\022\n\016CLIENTINTERNAL\020" +
      "c\022\n\n\006PLAYER\020e\022\007\n\003BAG\020f\022\t\n\005EQUIP\020g\022\n\n\006WUX" +
      "ING\020h\022\010\n\004TREE\020i\022\007\n\003MAP\020j\022\r\n\tSTEAL_ROB\020k\022" +
      "\t\n\005ARENA\020l\022\010\n\004SHOP\020m\022\014\n\010ACTIVITY\020n\022\013\n\007PA" +
      "YMENT\020oB4\n\036com.lz.game.platf.global.prot" +
      "oB\020ServiceNameProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
