// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bag_stru.proto

package com.lz.game.platf.gamelogic.commonstru.proto;

public final class BagStruProto {
  private BagStruProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum SlotType
      implements com.google.protobuf.ProtocolMessageEnum {
    WEAPON(0, 1),
    CLOTHE(1, 2),
    SHOES(2, 3),
    HAT(3, 4),
    JEWELRY(4, 5),
    FABAO1(5, 6),
    FABAO2(6, 7),
    FABAO3(7, 8),
    ;
    
    public static final int WEAPON_VALUE = 1;
    public static final int CLOTHE_VALUE = 2;
    public static final int SHOES_VALUE = 3;
    public static final int HAT_VALUE = 4;
    public static final int JEWELRY_VALUE = 5;
    public static final int FABAO1_VALUE = 6;
    public static final int FABAO2_VALUE = 7;
    public static final int FABAO3_VALUE = 8;
    
    
    public final int getNumber() { return value; }
    
    public static SlotType valueOf(int value) {
      switch (value) {
        case 1: return WEAPON;
        case 2: return CLOTHE;
        case 3: return SHOES;
        case 4: return HAT;
        case 5: return JEWELRY;
        case 6: return FABAO1;
        case 7: return FABAO2;
        case 8: return FABAO3;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SlotType>
        internalGetValueMap() {
      return internalValueMap;
    }
      private static com.google.protobuf.Internal.EnumLiteMap<SlotType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<SlotType>()
      {
          public SlotType findValueByNumber(int number)
          {
              return SlotType.valueOf(number);
          }
      };
      public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor()
      {
          return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType()
      {
          return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor()
      {
          return BagStruProto.getDescriptor().getEnumTypes().get(0);
      }
      private static final SlotType[] VALUES = {WEAPON, CLOTHE, SHOES, HAT, JEWELRY, FABAO1, FABAO2, FABAO3,};
      public static SlotType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc)
      {
          if (desc.getType() != getDescriptor())
          {
              throw new IllegalArgumentException("EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private SlotType(int index, int value)
      {
          this.index = index;
          this.value = value;
      }
      // @@protoc_insertion_point(enum_scope:proto.SlotType)
  }
    public interface CellItemInfoOrBuilder extends com.google.protobuf.MessageOrBuilder
    {
        // required int32 cell_num = 1;
        boolean hasCellNum();
        int getCellNum();
        // required bool is_null = 2;
        boolean hasIsNull();
        boolean getIsNull();
        // optional .proto.Item item = 3;
        boolean hasItem();
    ItemStruProto.Item getItem();
    ItemStruProto.ItemOrBuilder getItemOrBuilder();

    // optional int32 item_cnt = 4;
    boolean hasItemCnt();
    int getItemCnt();
  }
  public static final class CellItemInfo extends
      com.google.protobuf.GeneratedMessage
      implements CellItemInfoOrBuilder {
    // Use CellItemInfo.newBuilder() to construct.
    private CellItemInfo(Builder builder) {
      super(builder);
    }
    private CellItemInfo(boolean noInit) {}

    private static final CellItemInfo defaultInstance;
    public static CellItemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public CellItemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BagStruProto.internal_static_proto_CellItemInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BagStruProto.internal_static_proto_CellItemInfo_fieldAccessorTable;
    }

    private int bitField0_;
    // required int32 cell_num = 1;
    public static final int CELL_NUM_FIELD_NUMBER = 1;
    private int cellNum_;
    public boolean hasCellNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCellNum() {
      return cellNum_;
    }

    // required bool is_null = 2;
    public static final int IS_NULL_FIELD_NUMBER = 2;
    private boolean isNull_;
    public boolean hasIsNull() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsNull() {
      return isNull_;
    }

    // optional .proto.Item item = 3;
    public static final int ITEM_FIELD_NUMBER = 3;
    private ItemStruProto.Item item_;
    public boolean hasItem() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public ItemStruProto.Item getItem() {
      return item_;
    }
    public ItemStruProto.ItemOrBuilder getItemOrBuilder() {
      return item_;
    }

    // optional int32 item_cnt = 4;
    public static final int ITEM_CNT_FIELD_NUMBER = 4;
    private int itemCnt_;
    public boolean hasItemCnt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getItemCnt() {
      return itemCnt_;
    }

    private void initFields() {
      cellNum_ = 0;
      isNull_ = false;
      item_ = ItemStruProto.Item.getDefaultInstance();
      itemCnt_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCellNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsNull()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasItem()) {
        if (!getItem().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cellNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isNull_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, item_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, itemCnt_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cellNum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isNull_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, item_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, itemCnt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CellItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CellItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CellItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CellItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CellItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CellItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CellItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CellItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static CellItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CellItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CellItemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CellItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BagStruProto.internal_static_proto_CellItemInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BagStruProto.internal_static_proto_CellItemInfo_fieldAccessorTable;
      }

      // Construct using com.lz.game.platf.gamelogic.commonstru.proto.BagStruProto.CellItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cellNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isNull_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemBuilder_ == null) {
          item_ = ItemStruProto.Item.getDefaultInstance();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        itemCnt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CellItemInfo.getDescriptor();
      }

      public CellItemInfo getDefaultInstanceForType() {
        return CellItemInfo.getDefaultInstance();
      }

      public CellItemInfo build() {
        CellItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private CellItemInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        CellItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public CellItemInfo buildPartial() {
        CellItemInfo result = new CellItemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cellNum_ = cellNum_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isNull_ = isNull_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.itemCnt_ = itemCnt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CellItemInfo) {
          return mergeFrom((CellItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CellItemInfo other) {
        if (other == CellItemInfo.getDefaultInstance()) return this;
        if (other.hasCellNum()) {
          setCellNum(other.getCellNum());
        }
        if (other.hasIsNull()) {
          setIsNull(other.getIsNull());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        if (other.hasItemCnt()) {
          setItemCnt(other.getItemCnt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCellNum()) {

          return false;
        }
        if (!hasIsNull()) {

          return false;
        }
        if (hasItem()) {
          if (!getItem().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cellNum_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isNull_ = input.readBool();
              break;
            }
            case 26: {
              ItemStruProto.Item.Builder subBuilder = ItemStruProto.Item.newBuilder();
              if (hasItem()) {
                subBuilder.mergeFrom(getItem());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setItem(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              itemCnt_ = input.readInt32();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required int32 cell_num = 1;
      private int cellNum_ ;
      public boolean hasCellNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCellNum() {
        return cellNum_;
      }
      public Builder setCellNum(int value) {
        bitField0_ |= 0x00000001;
        cellNum_ = value;
        onChanged();
        return this;
      }
      public Builder clearCellNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cellNum_ = 0;
        onChanged();
        return this;
      }

      // required bool is_null = 2;
      private boolean isNull_ ;
      public boolean hasIsNull() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsNull() {
        return isNull_;
      }
      public Builder setIsNull(boolean value) {
        bitField0_ |= 0x00000002;
        isNull_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsNull() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isNull_ = false;
        onChanged();
        return this;
      }

      // optional .proto.Item item = 3;
      private ItemStruProto.Item item_ = ItemStruProto.Item.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder> itemBuilder_;
      public boolean hasItem() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public ItemStruProto.Item getItem() {
        if (itemBuilder_ == null) {
          return item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      public Builder setItem(ItemStruProto.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setItem(
          ItemStruProto.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeItem(ItemStruProto.Item value) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              item_ != ItemStruProto.Item.getDefaultInstance()) {
            item_ =
              ItemStruProto.Item.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = ItemStruProto.Item.getDefaultInstance();
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public ItemStruProto.Item.Builder getItemBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      public ItemStruProto.ItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder>
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder>(
                  item_,
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // optional int32 item_cnt = 4;
      private int itemCnt_ ;
      public boolean hasItemCnt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getItemCnt() {
        return itemCnt_;
      }
      public Builder setItemCnt(int value) {
        bitField0_ |= 0x00000008;
        itemCnt_ = value;
        onChanged();
        return this;
      }
      public Builder clearItemCnt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        itemCnt_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.CellItemInfo)
    }

    static {
      defaultInstance = new CellItemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.CellItemInfo)
  }

  public interface SlotItemInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .proto.SlotType slot_type = 1;
    boolean hasSlotType();
    SlotType getSlotType();

    // required bool is_null = 2;
    boolean hasIsNull();
    boolean getIsNull();

    // optional .proto.Item item = 3;
    boolean hasItem();
    ItemStruProto.Item getItem();
    ItemStruProto.ItemOrBuilder getItemOrBuilder();
  }
  public static final class SlotItemInfo extends
      com.google.protobuf.GeneratedMessage
      implements SlotItemInfoOrBuilder {
    // Use SlotItemInfo.newBuilder() to construct.
    private SlotItemInfo(Builder builder) {
      super(builder);
    }
    private SlotItemInfo(boolean noInit) {}

    private static final SlotItemInfo defaultInstance;
    public static SlotItemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public SlotItemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BagStruProto.internal_static_proto_SlotItemInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BagStruProto.internal_static_proto_SlotItemInfo_fieldAccessorTable;
    }

    private int bitField0_;
    // required .proto.SlotType slot_type = 1;
    public static final int SLOT_TYPE_FIELD_NUMBER = 1;
    private SlotType slotType_;
    public boolean hasSlotType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public SlotType getSlotType() {
      return slotType_;
    }

    // required bool is_null = 2;
    public static final int IS_NULL_FIELD_NUMBER = 2;
    private boolean isNull_;
    public boolean hasIsNull() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsNull() {
      return isNull_;
    }

    // optional .proto.Item item = 3;
    public static final int ITEM_FIELD_NUMBER = 3;
    private ItemStruProto.Item item_;
    public boolean hasItem() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public ItemStruProto.Item getItem() {
      return item_;
    }
    public ItemStruProto.ItemOrBuilder getItemOrBuilder() {
      return item_;
    }

    private void initFields() {
      slotType_ = SlotType.WEAPON;
      isNull_ = false;
      item_ = ItemStruProto.Item.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSlotType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsNull()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasItem()) {
        if (!getItem().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, slotType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isNull_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, item_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, slotType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isNull_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, item_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SlotItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SlotItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SlotItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SlotItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SlotItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SlotItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static SlotItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SlotItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SlotItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SlotItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SlotItemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SlotItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BagStruProto.internal_static_proto_SlotItemInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BagStruProto.internal_static_proto_SlotItemInfo_fieldAccessorTable;
      }

      // Construct using com.lz.game.platf.gamelogic.commonstru.proto.BagStruProto.SlotItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        slotType_ = SlotType.WEAPON;
        bitField0_ = (bitField0_ & ~0x00000001);
        isNull_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemBuilder_ == null) {
          item_ = ItemStruProto.Item.getDefaultInstance();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SlotItemInfo.getDescriptor();
      }

      public SlotItemInfo getDefaultInstanceForType() {
        return SlotItemInfo.getDefaultInstance();
      }

      public SlotItemInfo build() {
        SlotItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private SlotItemInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        SlotItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public SlotItemInfo buildPartial() {
        SlotItemInfo result = new SlotItemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.slotType_ = slotType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isNull_ = isNull_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SlotItemInfo) {
          return mergeFrom((SlotItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SlotItemInfo other) {
        if (other == SlotItemInfo.getDefaultInstance()) return this;
        if (other.hasSlotType()) {
          setSlotType(other.getSlotType());
        }
        if (other.hasIsNull()) {
          setIsNull(other.getIsNull());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSlotType()) {

          return false;
        }
        if (!hasIsNull()) {

          return false;
        }
        if (hasItem()) {
          if (!getItem().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              SlotType value = SlotType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                slotType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isNull_ = input.readBool();
              break;
            }
            case 26: {
              ItemStruProto.Item.Builder subBuilder = ItemStruProto.Item.newBuilder();
              if (hasItem()) {
                subBuilder.mergeFrom(getItem());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setItem(subBuilder.buildPartial());
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required .proto.SlotType slot_type = 1;
      private SlotType slotType_ = SlotType.WEAPON;
      public boolean hasSlotType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public SlotType getSlotType() {
        return slotType_;
      }
      public Builder setSlotType(SlotType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        slotType_ = value;
        onChanged();
        return this;
      }
      public Builder clearSlotType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        slotType_ = SlotType.WEAPON;
        onChanged();
        return this;
      }

      // required bool is_null = 2;
      private boolean isNull_ ;
      public boolean hasIsNull() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsNull() {
        return isNull_;
      }
      public Builder setIsNull(boolean value) {
        bitField0_ |= 0x00000002;
        isNull_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsNull() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isNull_ = false;
        onChanged();
        return this;
      }

      // optional .proto.Item item = 3;
      private ItemStruProto.Item item_ = ItemStruProto.Item.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder> itemBuilder_;
      public boolean hasItem() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public ItemStruProto.Item getItem() {
        if (itemBuilder_ == null) {
          return item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      public Builder setItem(ItemStruProto.Item value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setItem(
          ItemStruProto.Item.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeItem(ItemStruProto.Item value) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              item_ != ItemStruProto.Item.getDefaultInstance()) {
            item_ =
              ItemStruProto.Item.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = ItemStruProto.Item.getDefaultInstance();
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public ItemStruProto.Item.Builder getItemBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      public ItemStruProto.ItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder>
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ItemStruProto.Item, ItemStruProto.Item.Builder, ItemStruProto.ItemOrBuilder>(
                  item_,
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.SlotItemInfo)
    }

    static {
      defaultInstance = new SlotItemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.SlotItemInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CellItemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_CellItemInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SlotItemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_SlotItemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016bag_stru.proto\022\005proto\032\017item_stru.proto" +
      "\"^\n\014CellItemInfo\022\020\n\010cell_num\030\001 \002(\005\022\017\n\007is" +
      "_null\030\002 \002(\010\022\031\n\004item\030\003 \001(\0132\013.proto.Item\022\020" +
      "\n\010item_cnt\030\004 \001(\005\"^\n\014SlotItemInfo\022\"\n\tslot" +
      "_type\030\001 \002(\0162\017.proto.SlotType\022\017\n\007is_null\030" +
      "\002 \002(\010\022\031\n\004item\030\003 \001(\0132\013.proto.Item*g\n\010Slot" +
      "Type\022\n\n\006WEAPON\020\001\022\n\n\006CLOTHE\020\002\022\t\n\005SHOES\020\003\022" +
      "\007\n\003HAT\020\004\022\013\n\007JEWELRY\020\005\022\n\n\006FABAO1\020\006\022\n\n\006FAB" +
      "AO2\020\007\022\n\n\006FABAO3\020\010B>\n,com.lz.game.platf.g" +
      "amelogic.commonstru.protoB\014BagStruProtoH",
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_CellItemInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_CellItemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_CellItemInfo_descriptor,
              new String[] { "CellNum", "IsNull", "Item", "ItemCnt", },
              CellItemInfo.class,
              CellItemInfo.Builder.class);
          internal_static_proto_SlotItemInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_SlotItemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_SlotItemInfo_descriptor,
              new String[] { "SlotType", "IsNull", "Item", },
              SlotItemInfo.class,
              SlotItemInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ItemStruProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
